apiVersion: 1

datasources:
  - name: Prometheus
    uid: travel_any_prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.3.0
      timeInterval: 10s
